/*
 * Font decoder unit tests — prove font_decode_glyph() reproduces the
 * pre-compression Terminus tables byte-for-byte.
 *
 * golden_WxH.h (generated by scratchpad gen_goldens.py from the reference
 * tables) holds a CRC32 per codepoint for the regular and bold faces, plus
 * a few full-row spot glyphs for debuggable failures. The bold expectation
 * encodes the renderer semantics: the real bold glyph where the old bold
 * table stored one, the regular glyph everywhere else.
 */
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "unity.h"
#include "font.h"

#if FONT_RT_12X24
#include "golden_12x24.h"
#define TEST_SIZE   FONT_SIZE_12X24
#define TEST_W      12
#define TEST_H      24
#elif FONT_RT_10X20
#include "golden_10x20.h"
#define TEST_SIZE   FONT_SIZE_10X20
#define TEST_W      10
#define TEST_H      20
#else
#include "golden_8x16.h"
#define TEST_SIZE   FONT_SIZE_8X16
#define TEST_W      8
#define TEST_H      16
#endif

#define GB  FONT_GLYPH_BYTES(TEST_W, TEST_H)

/* zlib-compatible CRC32, bitwise (poly 0xEDB88320) */
static uint32_t crc32z(const uint8_t *p, size_t n)
{
    uint32_t c = 0xFFFFFFFFu;
    while (n--) {
        c ^= *p++;
        for (int k = 0; k < 8; k++)
            c = (c >> 1) ^ (0xEDB88320u & (0u - (c & 1)));
    }
    return c ^ 0xFFFFFFFFu;
}

void setUp(void)    {}
void tearDown(void) {}

static void test_geometry(void)
{
    TEST_ASSERT_EQUAL_INT(TEST_W, font_width());
    TEST_ASSERT_EQUAL_INT(TEST_H, font_height());
    TEST_ASSERT_EQUAL_UINT((unsigned)GB, (unsigned)font_glyph_bytes());
}

/* Every covered codepoint, regular face, must match its reference CRC. */
static void test_all_regular(void)
{
    uint8_t out[GB];
    int bad = 0;
    for (int i = 0; i < GOLDEN_NUM; i++) {
        font_decode_glyph(golden[i].cp, false, out);
        if (crc32z(out, GB) != golden[i].crc_reg) {
            if (bad < 10)
                printf("regular U+%04X mismatch\n", golden[i].cp);
            bad++;
        }
    }
    TEST_ASSERT_EQUAL_INT_MESSAGE(0, bad, "regular glyphs differ");
}

/* Every covered codepoint, bold semantics. */
static void test_all_bold(void)
{
    uint8_t out[GB];
    int bad = 0;
    for (int i = 0; i < GOLDEN_NUM; i++) {
        font_decode_glyph(golden[i].cp, true, out);
        if (crc32z(out, GB) != golden[i].crc_bold) {
            if (bad < 10)
                printf("bold U+%04X mismatch\n", golden[i].cp);
            bad++;
        }
    }
    TEST_ASSERT_EQUAL_INT_MESSAGE(0, bad, "bold glyphs differ");
}

/* Full-row comparison for a handful of glyphs — readable failure output. */
static void test_spot_rows(void)
{
    uint8_t out[GB];
    for (int i = 0; i < SPOT_NUM; i++) {
        font_decode_glyph(spot_reg[i].cp, false, out);
        TEST_ASSERT_EQUAL_MEMORY(spot_reg[i].rows, out, GB);
        font_decode_glyph(spot_bold[i].cp, true, out);
        TEST_ASSERT_EQUAL_MEMORY(spot_bold[i].rows, out, GB);
    }
}

/* An uncovered codepoint decodes as '?', bold included. */
static void test_fallback(void)
{
    uint8_t out[GB], q[GB];
    font_decode_glyph(0x003F, false, q);
    font_decode_glyph(0xE000, false, out);   /* private use — not in Terminus */
    TEST_ASSERT_EQUAL_MEMORY(q, out, GB);
    font_decode_glyph(0xE000, true, out);    /* outside bold subset too */
    TEST_ASSERT_EQUAL_MEMORY(q, out, GB);
}

/* U+0020 decodes to all-zero rows (the renderer's blank fast path must
 * agree with the decoder). */
static void test_blank(void)
{
    uint8_t out[GB], zero[GB];
    memset(zero, 0, GB);
    font_decode_glyph(0x0020, false, out);
    TEST_ASSERT_EQUAL_MEMORY(zero, out, GB);
}

/* The decoded-glyph cache is bounded (256 entries, 2-way) while the golden set
 * is ~1470 codepoints x 2 faces, so the sweeps above already overcommit it ~11x
 * and force constant eviction — every CRC they check goes through a fill.
 *
 * This covers what they do not: that a cache HIT returns the same bytes as the
 * fill that populated it, and that a refill after eviction is still correct.
 * A slot-indexing or victim-selection bug shows up here as a wrong glyph
 * rather than a corrupted one. */
static void test_cache_hit_and_refill(void)
{
    uint8_t first[GB], again[GB];
    int bad = 0;

    /* fill (or hit), then a guaranteed hit on the same key */
    for (int i = 0; i < GOLDEN_NUM; i++) {
        font_decode_glyph(golden[i].cp, false, first);
        font_decode_glyph(golden[i].cp, false, again);
        if (memcmp(first, again, GB) != 0) {
            if (bad < 10) printf("hit != fill at U+%04X\n", golden[i].cp);
            bad++;
        }
    }

    /* sweep the bold face to evict everything, then re-check a sample of the
     * regular face against its reference — a refill must be identical */
    for (int i = 0; i < GOLDEN_NUM; i++)
        font_decode_glyph(golden[i].cp, true, again);
    for (int i = 0; i < GOLDEN_NUM; i += 7) {
        font_decode_glyph(golden[i].cp, false, again);
        if (crc32z(again, GB) != golden[i].crc_reg) {
            if (bad < 10) printf("refill wrong at U+%04X\n", golden[i].cp);
            bad++;
        }
    }
    TEST_ASSERT_EQUAL_INT_MESSAGE(0, bad, "glyph cache hit/refill disagrees");
}

int main(void)
{
    font_init(TEST_SIZE);
    UNITY_BEGIN();
    RUN_TEST(test_geometry);
    RUN_TEST(test_spot_rows);
    RUN_TEST(test_all_regular);
    RUN_TEST(test_all_bold);
    RUN_TEST(test_fallback);
    RUN_TEST(test_blank);
    RUN_TEST(test_cache_hit_and_refill);
    return UNITY_END();
}
