#!/usr/bin/env python3
"""
gen_terminus.py -- generate components/font/terminusWxH.c from a Terminus BDF.

The output format matches the original hand-checked terminus8x16.c: one
`static const uintN_t font_range_XXXX_YYYY[]` array per contiguous codepoint
range (one line per glyph, FONT_HEIGHT row values, `// U+XXXX` comment),
followed by the FontRange directory. Rows are right-aligned: the leftmost
pixel is bit (FONT_WIDTH-1); rows are uint8_t for width 8, uint16_t above.

Usage:
    python gen_terminus.py <font.bdf> <out.c>              # generate
    python gen_terminus.py <font.bdf> --verify <ref.c>     # diff payload only
    python gen_terminus.py <normal.bdf> --bold <bold.bdf> <out.c>

Verify mode parses an existing generated/hand-made .c file and compares the
range list and every glyph row against the BDF conversion -- used to prove
the converter reproduces terminus8x16.c byte-for-byte before trusting it
for the sizes we cannot eyeball.

Bold mode emits a SPARSE companion table (terminus_bold_ranges): only the
glyphs inside BOLD_SUBSET whose bold bitmap actually differs from the normal
face. A lookup miss falls back to the normal glyph + the bold-pop color
effect, which is correct for identical glyphs and graceful for pruned ones.
"""

import re
import sys
from pathlib import Path


def parse_bdf(path):
    """Return (width, height, {codepoint: [row_int; height]})."""
    fbb = None                      # (w, h, xoff, yoff)
    glyphs = {}
    cp = None
    bbx = None
    rows = None
    in_bitmap = False

    for line in Path(path).read_text(encoding="utf-8", errors="replace").splitlines():
        if line.startswith("FONTBOUNDINGBOX"):
            _, w, h, xo, yo = line.split()
            fbb = (int(w), int(h), int(xo), int(yo))
        elif line.startswith("STARTCHAR"):
            cp, bbx, rows, in_bitmap = None, None, [], False
        elif line.startswith("ENCODING"):
            cp = int(line.split()[1])
        elif line.startswith("BBX"):
            _, bw, bh, bx, by = line.split()
            bbx = (int(bw), int(bh), int(bx), int(by))
        elif line.startswith("BITMAP"):
            in_bitmap = True
        elif line.startswith("ENDCHAR"):
            if cp is not None and 0 <= cp <= 0xFFFF:
                glyphs[cp] = compose_cell(fbb, bbx, rows, cp)
            in_bitmap = False
        elif in_bitmap:
            rows.append(line.strip())

    if fbb is None:
        sys.exit("no FONTBOUNDINGBOX in BDF")
    return fbb[0], fbb[1], glyphs


def compose_cell(fbb, bbx, hexrows, cp):
    """Place a BBX-cropped bitmap into the full font cell, right-aligned."""
    fw, fh, fxo, fyo = fbb
    bw, bh, bx, by = bbx
    start_row = (fh + fyo) - (bh + by)
    x_off = bx - fxo
    cell = [0] * fh
    mask = (1 << fw) - 1
    for i, hx in enumerate(hexrows):
        raw = int(hx, 16)
        bits = raw >> (len(hx) * 4 - bw)          # right-align bw bits
        shift = fw - x_off - bw
        val = bits << shift if shift >= 0 else bits >> -shift
        r = start_row + i
        if not 0 <= r < fh:
            if bits:
                print(f"warn: U+{cp:04X} row {r} clipped (set bits outside cell)")
            continue
        if val & ~mask:
            print(f"warn: U+{cp:04X} bits clipped horizontally")
        cell[r] = val & mask
    return cell


# Bold coverage — subset "A": the scripts a terminal actually bolds.
# Everything else falls back to the normal glyph + bold-pop brightening.
BOLD_SUBSET = [
    (0x0020, 0x007E),   # ASCII
    (0x00A0, 0x017F),   # Latin-1 supplement + Extended-A
    (0x0400, 0x045F),   # Cyrillic (basic Russian + extensions)
]


def contiguous_ranges(cps):
    out = []
    run = [cps[0], cps[0]]
    for c in cps[1:]:
        if c == run[1] + 1:
            run[1] = c
        else:
            out.append(tuple(run))
            run = [c, c]
    out.append(tuple(run))
    return out


HEADER = """\
/*
 * {w}x{h} bitmap glyph data derived from the Terminus Font ({src}).
 *
 * Copyright (c) 2020 Dimitar Zhekov <dimitar.zhekov@gmail.com>,
 * with Reserved Font Name "Terminus Font".
 *
 * Licensed under the SIL Open Font License, Version 1.1 — see the full text
 * in components/font/LICENSE. This file is NOT covered by the repository's
 * MIT license.
 *
 * Generated by tools/gen_terminus.py — do not edit by hand.
 */
#include "terminus_font.h"
#include <stddef.h>

#if FONT_WIDTH == {w} && FONT_HEIGHT == {h}

"""


def emit_c(width, height, glyphs, src_name, out_path):
    cps = sorted(glyphs)
    ranges = contiguous_ranges(cps)
    ctype = "uint8_t" if width <= 8 else "uint16_t"
    fmt = "0x{:02X}" if width <= 8 else "0x{:04X}"

    parts = [HEADER.format(w=width, h=height, src=src_name)]
    for lo, hi in ranges:
        parts.append(f"static const {ctype} font_range_{lo:04X}_{hi:04X}[] = {{\n")
        for cp in range(lo, hi + 1):
            vals = ", ".join(fmt.format(v) for v in glyphs[cp])
            parts.append(f"    {vals}, // U+{cp:04X}\n")
        parts.append("};\n\n")

    parts.append("const FontRange terminus_ranges[] = {\n")
    for lo, hi in ranges:
        parts.append(f"    {{0x{lo:04X}, 0x{hi:04X}, font_range_{lo:04X}_{hi:04X}}},\n")
    parts.append("};\n\n")
    parts.append(f"const int terminus_num_ranges = {len(ranges)};\n\n")
    parts.append(f"#endif /* FONT_WIDTH == {width} && FONT_HEIGHT == {height} */\n")

    Path(out_path).write_text("".join(parts), encoding="utf-8", newline="\n")
    total = len(cps)
    bytes_per = height * (1 if width <= 8 else 2)
    print(f"{out_path}: {len(ranges)} ranges, {total} glyphs, "
          f"{total * bytes_per} data bytes")


BOLD_HEADER = """\
/*
 * {w}x{h} BOLD glyph data derived from the Terminus Font ({src}).
 * Sparse companion to the normal table: subset-A coverage (ASCII,
 * Latin-1/Extended-A, Cyrillic), differ-only — identical-to-normal glyphs
 * are pruned, the renderer falls back to the normal glyph on a miss.
 *
 * Copyright (c) 2020 Dimitar Zhekov <dimitar.zhekov@gmail.com>,
 * with Reserved Font Name "Terminus Font".
 *
 * Licensed under the SIL Open Font License, Version 1.1 — see the full text
 * in components/font/LICENSE. This file is NOT covered by the repository's
 * MIT license.
 *
 * Generated by tools/gen_terminus.py — do not edit by hand.
 */
#include "terminus_font.h"
#include <stddef.h>

#if FONT_BOLD_ENABLED && FONT_WIDTH == {w} && FONT_HEIGHT == {h}

"""


def emit_bold_c(width, height, normal, bold, src_name, out_path):
    """Emit the sparse bold table: BOLD_SUBSET ∩ differ-from-normal."""
    cps = sorted(cp for cp in bold
                 if any(lo <= cp <= hi for lo, hi in BOLD_SUBSET)
                 and bold[cp] != normal[cp])
    if not cps:
        sys.exit("bold: nothing differs — wrong BDF pair?")
    ranges = contiguous_ranges(cps)
    ctype = "uint8_t" if width <= 8 else "uint16_t"
    fmt = "0x{:02X}" if width <= 8 else "0x{:04X}"

    parts = [BOLD_HEADER.format(w=width, h=height, src=src_name)]
    for lo, hi in ranges:
        parts.append(f"static const {ctype} font_bold_{lo:04X}_{hi:04X}[] = {{\n")
        for cp in range(lo, hi + 1):
            vals = ", ".join(fmt.format(v) for v in bold[cp])
            parts.append(f"    {vals}, // U+{cp:04X}\n")
        parts.append("};\n\n")

    parts.append("const FontRange terminus_bold_ranges[] = {\n")
    for lo, hi in ranges:
        parts.append(f"    {{0x{lo:04X}, 0x{hi:04X}, font_bold_{lo:04X}_{hi:04X}}},\n")
    parts.append("};\n\n")
    parts.append(f"const int terminus_num_bold_ranges = {len(ranges)};\n\n")
    parts.append(f"#endif /* FONT_BOLD_ENABLED && {width}x{height} */\n")

    Path(out_path).write_text("".join(parts), encoding="utf-8", newline="\n")
    bytes_per = height * (1 if width <= 8 else 2)
    print(f"{out_path}: {len(ranges)} ranges, {len(cps)} bold glyphs, "
          f"{len(cps) * bytes_per} data bytes")


def parse_ref_c(path):
    """Extract {codepoint: [row_int]} + range list from an existing table .c."""
    text = Path(path).read_text(encoding="utf-8")
    arrays = {}
    for m in re.finditer(
            r"font_range_([0-9A-F]{4})_([0-9A-F]{4})\[\]\s*=\s*\{(.*?)\};",
            text, re.S):
        lo, hi = int(m.group(1), 16), int(m.group(2), 16)
        vals = [int(v, 16) for v in re.findall(r"0x[0-9A-Fa-f]+", m.group(3))]
        arrays[(lo, hi)] = vals
    ranges = [(int(a, 16), int(b, 16)) for a, b in re.findall(
        r"\{0x([0-9A-F]{4}), 0x([0-9A-F]{4}), font_range_", text)]
    return arrays, ranges


def verify(width, height, glyphs, ref_path):
    arrays, ranges = parse_ref_c(ref_path)
    want = contiguous_ranges(sorted(glyphs))
    if want != ranges:
        only_bdf = set(want) - set(ranges)
        only_ref = set(ranges) - set(want)
        sys.exit(f"RANGE MISMATCH\n only in BDF: {sorted(only_bdf)}\n"
                 f" only in ref: {sorted(only_ref)}")
    bad = 0
    for (lo, hi), vals in arrays.items():
        for i, cp in enumerate(range(lo, hi + 1)):
            ref_rows = vals[i * height:(i + 1) * height]
            if ref_rows != glyphs[cp]:
                bad += 1
                if bad <= 10:
                    print(f"U+{cp:04X} differs:\n  ref: {ref_rows}\n"
                          f"  bdf: {glyphs[cp]}")
    n = sum(hi - lo + 1 for lo, hi in ranges)
    if bad:
        sys.exit(f"FAIL: {bad}/{n} glyphs differ")
    print(f"OK: {n} glyphs, {len(ranges)} ranges — BDF conversion matches {ref_path}")


def main():
    if len(sys.argv) == 5 and sys.argv[2] == "--bold":
        width, height, normal = parse_bdf(sys.argv[1])
        wb, hb, bold = parse_bdf(sys.argv[3])
        if (wb, hb) != (width, height) or normal.keys() != bold.keys():
            sys.exit("bold: size or coverage mismatch between faces")
        emit_bold_c(width, height, normal, bold, Path(sys.argv[3]).name,
                    sys.argv[4])
        return
    if len(sys.argv) != 3 and not (len(sys.argv) == 4 and sys.argv[2] == "--verify"):
        sys.exit(__doc__)
    bdf = sys.argv[1]
    width, height, glyphs = parse_bdf(bdf)
    if sys.argv[2] == "--verify":
        verify(width, height, glyphs, sys.argv[3])
    else:
        emit_c(width, height, glyphs, Path(bdf).name, sys.argv[2])


if __name__ == "__main__":
    main()
